# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='fastapi',
    version='0.63.0',
    description='FastAPI framework, high performance, easy to learn, fast to code, ready for production',
    python_requires='>=3.6',
    project_urls={
        "Documentation": "https://fastapi.tiangolo.com/",
        "homepage": "https://github.com/tiangolo/fastapi"
    },
    author='Sebastián Ramírez',
    author_email='tiangolo@gmail.com',
    classifiers=[
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3', 'Programming Language :: Python',
        'Topic :: Internet',
        'Topic :: Software Development :: Libraries :: Application Frameworks',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development', 'Typing :: Typed',
        'Development Status :: 4 - Beta', 'Environment :: Web Environment',
        'Framework :: AsyncIO', 'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Internet :: WWW/HTTP :: HTTP Servers',
        'Topic :: Internet :: WWW/HTTP'
    ],
    packages=[
        'fastapi', 'fastapi.dependencies', 'fastapi.middleware',
        'fastapi.openapi', 'fastapi.security'
    ],
    package_dir={"": "."},
    package_data={"fastapi": ["*.typed"]},
    install_requires=['pydantic<2.0.0,>=1.0.0', 'starlette==0.14.1', "setuptools==50.3.2"],
    extras_require={
        "all": [
            "aiofiles<0.6.0,>=0.5.0", "async-exit-stack<2.0.0,>=1.0.1",
            "async-generator<2.0.0,>=1.10", "email-validator<2.0.0,>=1.1.1",
            "graphene<3.0.0,>=2.1.8", "itsdangerous<2.0.0,>=1.1.0",
            "jinja2<3.0.0,>=2.11.2", "orjson<4.0.0,>=3.2.1",
            "python-multipart<0.0.6,>=0.0.5", "pyyaml<6.0.0,>=5.3.1",
            "requests<3.0.0,>=2.24.0", "ujson<5.0.0,>=4.0.1",
            "uvicorn<0.12.0,>=0.11.5", "setuptools==50.3.2"
        ],
        "dev": [
            "autoflake<2.0.0,>=1.3.1", "passlib[bcrypt]<2.0.0,>=1.7.2",
            "python-jose[cryptography]<4.0.0,>=3.1.0", "setuptools==50.3.2"
        ],
        "doc": [
            "markdown-include<0.6.0,>=0.5.1", "mkdocs<2.0.0,>=1.1.2",
            "mkdocs-markdownextradata-plugin<0.2.0,>=0.1.7",
            "mkdocs-material<7.0.0,>=6.1.4", "pyyaml<6.0.0,>=5.3.1",
            "typer<0.4.0,>=0.3.0", "typer-cli<0.0.10,>=0.0.9"
        ],
        "test": [
            "aiofiles<0.6.0,>=0.5.0", "async-exit-stack<2.0.0,>=1.0.1",
            "async-generator<2.0.0,>=1.10", "black==19.10b0",
            "databases[sqlite]<0.4.0,>=0.3.2", "email-validator<2.0.0,>=1.1.1",
            "flake8<4.0.0,>=3.8.3", "flask<2.0.0,>=1.1.2",
            "httpx<0.15.0,>=0.14.0", "isort<6.0.0,>=5.0.6", "mypy==0.782",
            "orjson<4.0.0,>=3.2.1", "peewee<4.0.0,>=3.13.3", "pytest==5.4.3",
            "pytest-asyncio<0.15.0,>=0.14.0", "pytest-cov==2.10.0",
            "python-multipart<0.0.6,>=0.0.5", "requests<3.0.0,>=2.24.0",
            "sqlalchemy<2.0.0,>=1.3.18", "ujson<5.0.0,>=4.0.1"
        ]
    },
)
